// client/src/lib/widgets/WidgetHost.tsx
// Container (organism): positions one widget and wires its sensor to the presentational meter.
// The meter stays prop-only; all subscription lives here. In edit mode a transparent overlay drags
// the widget and corner/edge handles resize it; both report rect changes up via the `onChange`
// callback. The seven Svelte dispatch events become seven callback props.
import {
	useRef,
	useState,
	type MouseEvent as ReactMouseEvent,
	type PointerEvent as ReactPointerEvent
} from 'react';
import type { TelemetryHub } from '../core/telemetry';
import type { Rect, WidgetInstance } from '../core/layout';
import { moveRect, resizeRect, type ResizeHandle } from '../core/geometry';
import { getMeta } from '../core/widget';
import { registry } from './registry';
import { useSensor } from './useSensor';
import './WidgetHost.css';

type Props = {
	hub: TelemetryHub;
	instance: WidgetInstance;
	editMode?: boolean;
	selected?: boolean;
	grid?: number;
	// Zoom factor of the surrounding world layer; pointer deltas (screen px) are divided by it.
	scale?: number;
	// Absolute rect to render at (the solver's result); defaults to instance.rect (floating).
	rect?: Rect;
	// Floating widgets free-move/resize; in-flow widgets are solver-positioned (select-only here).
	movable?: boolean;
	// What clicking selects (a group's descendants select the group), defaults to this widget.
	selectId?: string;
	// Styling hooks: the unique DOM id + the group/def this widget belongs to (data-w/def/group).
	domId?: string;
	defId?: string;
	groupId?: string;
	onChange?: (e: { id: string; rect: Rect }) => void;
	onCommit?: () => void;
	onSelect?: (e: { id: string }) => void;
	onDragOver?: (e: { id: string; x: number; y: number }) => void;
	onDrop?: (e: { id: string; x: number; y: number }) => void;
	onContextMenu?: (e: { id: string; x: number; y: number }) => void;
	onControl?: (e: { id: string; sensor?: string; domain: string; service: string }) => void;
};

const HANDLES: ResizeHandle[] = ['nw', 'n', 'ne', 'e', 'se', 's', 'sw', 'w'];
// A press only becomes a drag past this screen-px slop; below it the press is a click that just
// selects. Without this, clicking an in-flow widget dispatches a `drop` = moves it to a slot.
const DRAG_SLOP = 3;

export default function WidgetHost({
	hub,
	instance,
	editMode = false,
	selected = false,
	grid = 8,
	scale = 1,
	rect: rectProp,
	movable = true,
	selectId: selectIdProp,
	domId: domIdProp,
	defId,
	groupId,
	onChange,
	onCommit,
	onSelect,
	onDragOver,
	onDrop,
	onContextMenu,
	onControl
}: Props) {
	const rect = rectProp ?? instance.rect;
	const selectId = selectIdProp ?? instance.id;
	const domId = domIdProp ?? instance.id;

	// A sentinel id keeps the hook valid for self-sourcing widgets (no sensor).
	const sensorState = useSensor(hub, instance.sensor ?? '__none__');
	const Comp = registry[instance.type];
	// How this widget binds to its sensor drives the meter's value-shape (Phase 8).
	const binds = getMeta(instance.type)?.binds ?? 'scalar';
	const scalar =
		sensorState.value && sensorState.value.kind === 'scalar' ? sensorState.value.value : null;
	const rawValue = sensorState.value ? sensorState.value.value : null;
	const history = sensorState.history;

	// Authoritative drag bookkeeping in a ref (read synchronously by move/end — no stale closures);
	// only the render-affecting bits (active class + ghost transform) live in state.
	const drag = useRef<{
		action: 'move' | 'flow' | ResizeHandle | null;
		startX: number;
		startY: number;
		startRect: Rect;
		moved: boolean;
	}>({ action: null, startX: 0, startY: 0, startRect: instance.rect, moved: false });
	const [action, setAction] = useState<'move' | 'flow' | ResizeHandle | null>(null);
	const [ghost, setGhost] = useState({ dx: 0, dy: 0 });

	// A plugin widget (e.g. an HA light) asks to actuate; the host adds its identity and bubbles up —
	// the side-effecting Tauri call lives in the container (Canvas), not here (AGENTS.md §5/§6).
	const handleControl = (e: { domain: string; service: string }) =>
		onControl?.({ id: instance.id, sensor: instance.sensor, ...e });

	const handleContextMenu = (e: ReactMouseEvent) => {
		if (!editMode) return;
		e.preventDefault();
		e.stopPropagation();
		onSelect?.({ id: selectId });
		onContextMenu?.({ id: selectId, x: e.clientX, y: e.clientY });
	};

	function begin(kind: 'move' | ResizeHandle, e: ReactPointerEvent) {
		if (e.button !== 0) return; // left-button only; middle-drag is reserved for panning
		if (!editMode) return;
		onSelect?.({ id: selectId });
		const d = drag.current;
		d.moved = false;
		if (!movable) {
			// In-flow widgets ghost-drag to reorder/reparent; the solver owns their base position, so
			// we translate a ghost and only mutate the tree on drop (5e).
			d.action = 'flow';
			d.startX = e.clientX;
			d.startY = e.clientY;
			setAction('flow');
			setGhost({ dx: 0, dy: 0 });
			e.currentTarget.setPointerCapture(e.pointerId);
			e.preventDefault();
			e.stopPropagation();
			return;
		}
		d.action = kind;
		d.startX = e.clientX;
		d.startY = e.clientY;
		d.startRect = rect;
		setAction(kind);
		e.currentTarget.setPointerCapture(e.pointerId);
		e.preventDefault();
		e.stopPropagation();
	}

	function move(e: ReactPointerEvent) {
		const d = drag.current;
		if (d.action === null) return;
		// Below the slop the press is still a click-to-select: don't ghost, move, resize or preview.
		if (!d.moved) {
			if (
				Math.abs(e.clientX - d.startX) <= DRAG_SLOP &&
				Math.abs(e.clientY - d.startY) <= DRAG_SLOP
			)
				return;
			d.moved = true;
		}
		if (d.action === 'flow') {
			setGhost({ dx: (e.clientX - d.startX) / scale, dy: (e.clientY - d.startY) / scale });
			onDragOver?.({ id: selectId, x: e.clientX, y: e.clientY });
			return;
		}
		const dx = (e.clientX - d.startX) / scale;
		const dy = (e.clientY - d.startY) / scale;
		const next =
			d.action === 'move'
				? moveRect(d.startRect, dx, dy, grid)
				: resizeRect(d.startRect, d.action, dx, dy, grid);
		onChange?.({ id: instance.id, rect: next });
		// A floating widget dragged over the flow tree can dock there (checked on commit).
		if (d.action === 'move') onDragOver?.({ id: selectId, x: e.clientX, y: e.clientY });
	}

	function end(e: ReactPointerEvent) {
		const d = drag.current;
		if (d.action === null) return;
		const wasFlow = d.action === 'flow';
		const didMove = d.moved;
		d.action = null;
		setAction(null);
		if (wasFlow) {
			setGhost({ dx: 0, dy: 0 });
			// A click (no real movement) just selects — only an actual drag reparents/reorders.
			if (didMove) onDrop?.({ id: selectId, x: e.clientX, y: e.clientY });
			return;
		}
		// Likewise a click on a floating widget selects without a no-op move/commit.
		if (didMove) onCommit?.();
	}

	const cls = ['widget'];
	if (editMode) cls.push('editable');
	if (selected) cls.push('selected');
	if (action !== null) cls.push('active');
	if (!editMode && instance.interactive) cls.push('catch');
	if (action === 'flow') cls.push('dragging');

	return (
		<div
			className={cls.join(' ')}
			style={{
				left: `${rect.x}px`,
				top: `${rect.y}px`,
				width: `${rect.w}px`,
				height: `${rect.h}px`,
				transform: `translate(${ghost.dx}px, ${ghost.dy}px)`
			}}
			data-w={domId}
			data-type={instance.type}
			data-sensor={instance.sensor}
			data-def={defId}
			data-group={groupId}
			onContextMenu={handleContextMenu}
		>
			{Comp ? (
				!instance.sensor || binds === 'none' ? (
					<Comp {...instance.config} onControl={handleControl} />
				) : binds === 'json' || binds === 'text' ? (
					<Comp value={rawValue} {...instance.config} onControl={handleControl} />
				) : (
					<Comp value={scalar} history={history} {...instance.config} onControl={handleControl} />
				)
			) : (
				<div className="missing">?{instance.type}</div>
			)}

			{editMode && (
				<>
					<button
						type="button"
						className="drag-overlay"
						aria-label={`Move ${instance.type} widget`}
						onPointerDown={(e) => begin('move', e)}
						onPointerMove={move}
						onPointerUp={end}
					/>
					{movable &&
						HANDLES.map((handle) => (
							<button
								key={handle}
								type="button"
								className={`handle ${handle}`}
								aria-label={`Resize ${handle}`}
								onPointerDown={(e) => begin(handle, e)}
								onPointerMove={move}
								onPointerUp={end}
							/>
						))}
				</>
			)}
		</div>
	);
}

// client/src/lib/widgets/WidgetHost.svelte
<script lang="ts">
	// Container (organism): positions one widget and wires its sensor to the
	// presentational meter. The meter stays prop-only; all subscription lives here.
	// In edit mode a transparent overlay drags the widget and corner/edge handles
	// resize it; both report rect changes up via the `change` event.
	import { createEventDispatcher } from 'svelte';
	import type { TelemetryHub } from '../core/telemetry';
	import type { Rect, WidgetInstance } from '../core/layout';
	import { moveRect, resizeRect, type ResizeHandle } from '../core/geometry';
	import { getMeta } from '../core/widget';
	import { registry } from './registry';
	import { sensorStore } from './sensorStore';

	export let hub: TelemetryHub;
	export let instance: WidgetInstance;
	export let editMode = false;
	export let selected = false;
	export let grid = 8;
	// The zoom factor of the surrounding world layer (studio zoom-to-fit). Pointer deltas are
	// in screen px, so they're divided by `scale` to become world px before moving/resizing.
	// 1 in the overlay (no zoom), so the math is unchanged there.
	export let scale = 1;
	// Absolute rect to render at (the solver's result). For floating widgets this equals
	// instance.rect; for in-flow widgets the solver dictates it.
	export let rect: Rect = instance.rect;
	// Floating widgets free-move/resize; in-flow widgets are positioned by the solver, so
	// they're select-only here (reorder/reparent happens via the outline or drag — 5e).
	export let movable = true;
	// What clicking selects — usually this widget, but a group's descendants select the
	// group (the selectable unit), so the host is told explicitly.
	export let selectId: string = instance.id;
	// Styling hooks (Phase 7): the unique DOM id + the group/def this widget belongs to,
	// so theme/def/instance CSS can target it (data-w / data-def / data-group / data-type).
	export let domId: string = instance.id;
	export let defId: string | undefined = undefined;
	export let groupId: string | undefined = undefined;

	const HANDLES: ResizeHandle[] = ['nw', 'n', 'ne', 'e', 'se', 's', 'sw', 'w'];
	const dispatch = createEventDispatcher<{
		change: { id: string; rect: Rect };
		commit: void;
		select: { id: string };
		dragover: { id: string; x: number; y: number };
		drop: { id: string; x: number; y: number };
		contextmenu: { id: string; x: number; y: number };
		control: { id: string; sensor?: string; domain: string; service: string };
	}>();

	// A plugin widget (e.g. an HA light) asks to actuate; the host adds its identity and
	// bubbles up — the side-effecting Tauri call lives in the container (Canvas), not here
	// and not in the prop-only meter (AGENTS.md §5/§6).
	function onControl(event: CustomEvent<{ domain: string; service: string }>) {
		dispatch('control', { id: instance.id, sensor: instance.sensor, ...event.detail });
	}

	function onContextMenu(event: MouseEvent) {
		if (!editMode) return;
		event.preventDefault();
		event.stopPropagation();
		dispatch('select', { id: selectId });
		dispatch('contextmenu', { id: selectId, x: event.clientX, y: event.clientY });
	}

	// A sentinel id keeps `$store` a valid store for self-sourcing widgets (no sensor).
	$: store = sensorStore(hub, instance.sensor ?? '__none__');
	$: comp = registry[instance.type];
	// How this widget type binds to its sensor drives what value-shape the meter gets
	// (Phase 8). scalar/series stay byte-identical to before (value=number + history);
	// json/text widgets (HA) get the raw SensorValue payload as `value`.
	$: binds = getMeta(instance.type)?.binds ?? 'scalar';
	$: scalar = $store.value && $store.value.kind === 'scalar' ? $store.value.value : null;
	$: rawValue = $store.value ? $store.value.value : null;
	$: history = $store.history;

	let action: 'move' | 'flow' | ResizeHandle | null = null;
	let startX = 0;
	let startY = 0;
	let startRect: Rect = instance.rect;
	// Visual offset while ghost-dragging an in-flow widget (the model only changes on drop).
	let ghostDx = 0;
	let ghostDy = 0;
	// A press only becomes a drag past this screen-px slop; below it the press is a click that just
	// selects. Without this, clicking an in-flow widget dispatches a `drop` = moves it to a slot.
	const DRAG_SLOP = 3;
	let moved = false;

	function begin(kind: 'move' | ResizeHandle, event: PointerEvent) {
		if (event.button !== 0) return; // left-button only; middle-drag is reserved for panning
		if (!editMode) return;
		dispatch('select', { id: selectId });
		moved = false;
		if (!movable) {
			// In-flow widgets ghost-drag to reorder/reparent; the solver owns their base
			// position, so we translate a ghost and only mutate the tree on drop (5e).
			action = 'flow';
			startX = event.clientX;
			startY = event.clientY;
			ghostDx = 0;
			ghostDy = 0;
			(event.currentTarget as Element).setPointerCapture(event.pointerId);
			event.preventDefault();
			event.stopPropagation();
			return;
		}
		action = kind;
		startX = event.clientX;
		startY = event.clientY;
		startRect = rect;
		(event.currentTarget as Element).setPointerCapture(event.pointerId);
		event.preventDefault();
		event.stopPropagation();
	}

	function move(event: PointerEvent) {
		if (action === null) return;
		// Below the slop the press is still a click-to-select: don't ghost, move, resize or preview.
		if (!moved) {
			if (
				Math.abs(event.clientX - startX) <= DRAG_SLOP &&
				Math.abs(event.clientY - startY) <= DRAG_SLOP
			)
				return;
			moved = true;
		}
		if (action === 'flow') {
			// World-space offset (the ghost lives inside the scaled world; screen delta / scale
			// renders back to the same screen distance the cursor moved).
			ghostDx = (event.clientX - startX) / scale;
			ghostDy = (event.clientY - startY) / scale;
			dispatch('dragover', { id: selectId, x: event.clientX, y: event.clientY });
			return;
		}
		const dx = (event.clientX - startX) / scale;
		const dy = (event.clientY - startY) / scale;
		const next =
			action === 'move'
				? moveRect(startRect, dx, dy, grid)
				: resizeRect(startRect, action, dx, dy, grid);
		dispatch('change', { id: instance.id, rect: next });
		// A floating widget dragged over the flow tree can dock there (checked on commit).
		if (action === 'move')
			dispatch('dragover', { id: selectId, x: event.clientX, y: event.clientY });
	}

	function end(event: PointerEvent) {
		if (action === null) return;
		const wasFlow = action === 'flow';
		const didMove = moved;
		action = null;
		if (wasFlow) {
			ghostDx = 0;
			ghostDy = 0;
			// A click (no real movement) just selects — only an actual drag reparents/reorders.
			if (didMove) dispatch('drop', { id: selectId, x: event.clientX, y: event.clientY });
			return;
		}
		// Likewise a click on a floating widget selects without a no-op move/commit.
		if (didMove) dispatch('commit');
	}
</script>

<div
	class="widget"
	class:editable={editMode}
	class:selected
	class:active={action !== null}
	class:catch={!editMode && instance.interactive}
	class:dragging={action === 'flow'}
	style="left: {rect.x}px; top: {rect.y}px; width: {rect.w}px; height: {rect.h}px; transform: translate({ghostDx}px, {ghostDy}px)"
	data-w={domId}
	data-type={instance.type}
	data-sensor={instance.sensor}
	data-def={defId}
	data-group={groupId}
	on:contextmenu={onContextMenu}
>
	{#if comp}
		{#if !instance.sensor || binds === 'none'}
			<svelte:component this={comp} {...instance.config} on:control={onControl} />
		{:else if binds === 'json' || binds === 'text'}
			<svelte:component this={comp} value={rawValue} {...instance.config} on:control={onControl} />
		{:else}
			<svelte:component
				this={comp}
				value={scalar}
				{history}
				{...instance.config}
				on:control={onControl}
			/>
		{/if}
	{:else}
		<div class="missing">?{instance.type}</div>
	{/if}

	{#if editMode}
		<button
			type="button"
			class="drag-overlay"
			aria-label="Move {instance.type} widget"
			on:pointerdown={(e) => begin('move', e)}
			on:pointermove={move}
			on:pointerup={end}
		/>
		{#if movable}
			{#each HANDLES as handle (handle)}
				<button
					type="button"
					class="handle {handle}"
					aria-label="Resize {handle}"
					on:pointerdown={(e) => begin(handle, e)}
					on:pointermove={move}
					on:pointerup={end}
				/>
			{/each}
		{/if}
	{/if}
</div>

<style>
	.widget {
		position: absolute;
	}

	/* Interactive widgets catch clicks in passive mode (the canvas is otherwise
	   pointer-events:none). The cursor watcher gates this at the OS level. */
	.widget.catch {
		pointer-events: auto;
	}

	.widget.editable {
		outline: 1px dashed rgba(119, 196, 211, 0.7);
		outline-offset: 2px;
	}

	.widget.active {
		outline-style: solid;
	}

	.widget.selected {
		outline-color: rgb(119, 196, 211);
		outline-style: solid;
	}

	.drag-overlay {
		position: absolute;
		inset: 0;
		margin: 0;
		padding: 0;
		border: none;
		background: transparent;
		cursor: move;
	}

	.widget.dragging {
		z-index: 10;
		opacity: 0.85;
	}

	.handle {
		position: absolute;
		width: 8px;
		height: 8px;
		margin: 0;
		padding: 0;
		box-sizing: border-box;
		border: 1px solid rgba(119, 196, 211, 0.9);
		background: #0b0b0b;
		z-index: 1;
	}

	.handle.n {
		top: -4px;
		left: calc(50% - 4px);
		cursor: ns-resize;
	}

	.handle.s {
		bottom: -4px;
		left: calc(50% - 4px);
		cursor: ns-resize;
	}

	.handle.e {
		right: -4px;
		top: calc(50% - 4px);
		cursor: ew-resize;
	}

	.handle.w {
		left: -4px;
		top: calc(50% - 4px);
		cursor: ew-resize;
	}

	.handle.ne {
		top: -4px;
		right: -4px;
		cursor: nesw-resize;
	}

	.handle.nw {
		top: -4px;
		left: -4px;
		cursor: nwse-resize;
	}

	.handle.se {
		bottom: -4px;
		right: -4px;
		cursor: nwse-resize;
	}

	.handle.sw {
		bottom: -4px;
		left: -4px;
		cursor: nesw-resize;
	}

	.missing {
		font-family: monospace;
		font-size: 11px;
		color: rgba(255, 120, 120, 0.9);
	}
</style>
